# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Unit tests
      env:
        DEFAULT_BRANCH: master
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        apiKey: ${{ secrets.APIKEY }}
      run: |
        npm install
        npm run lint
        ###
        # Configure Angular first!
        ####
        npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
        # npm run webdriver-update-ci
        # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
        ####
        #npm run ng -- deploy --base-href=/airther/ --name="Pages Bot" --email=pagesBot@example.org
  e2e-tests-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: e2e tests
      env:
        DEFAULT_BRANCH: master
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run lint
        ###
        # Configure Angular first!
        ####
        # npm run webdriver-update-ci
        npm run e2e --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
        ####
        #npm run ng -- deploy --base-href=/airther/ --name="Pages Bot" --email=pagesBot@example.org   
